### ISSUE TITLE
click events

### ISSUE THREAD

**Issue by rbartholomay** [uwu-loli/notify-manager-electron#1]
Hi there,

this is really nice. The only thing i missing is handling click events (e.g. from buttons) and a closebox. Any change that a newer version can handle this?

Bye, René

**Comment by ghost** [comment]
Hello.

Your suggestion is implemented in version 1.1.0 ([Release](https://github.com/fydne/notify-manager-electron/releases/tag/1.1.0))

In addition to the current click events, you can add your own buttons by using html.
If required, I can add in next version the ability to call IpcRenderer from html buttons. Write about it here if you need it.

Good day, fydne

**Comment by rbartholomay** [comment]
thanks a lot!

yes, it will be great if you can add rhis. So i can handle different behaviours on buttton like "closebox", details...

Bye, René

**Comment by ghost** [comment]
IPC were added in version [1.1.1](https://github.com/fydne/notify-manager-electron/releases/tag/1.1.1)
You can see an example of their use [here](https://github.com/fydne/notify-manager-electron/tree/main/tests/reply)
